<a href="https://colab.research.google.com/github/kursatkara/MAE_5020_Spring_2026/blob/master/03_4_0_Background.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

A = np.array([[1, 2, 9],
              [8, 5, 6],
              [7, 16, 9]])

print("A matrix:")
print(A,"\n")

print("Flattened A matrix:")
print(A.flatten(),"\n")

print("mean of A, (flattened)      :",np.mean(A))
print("mean of A, axis = 0 (column):", np.mean(A,axis=0))
print("mean of A, axis = 1 (row)   :",np.mean(A,axis=1),"\n")

print("variance of A               :",np.var(A))
print("std deviation of A          :",np.std(A))
print("std deviation of A          :",np.sqrt(np.var(A)))

# Calculate variance and stddev of columns of A


# Calculate variance and stddev of rows of A


A matrix:
[[ 1  2  9]
 [ 8  5  6]
 [ 7 16  9]] 

Flattened A matrix:
[ 1  2  9  8  5  6  7 16  9] 

mean of A, (flattened)      : 7.0
mean of A, axis = 0 (column): [5.33333333 7.66666667 8.        ]
mean of A, axis = 1 (row)   : [ 4.          6.33333333 10.66666667] 

variance of A               : 17.333333333333332
std deviation of A          : 4.163331998932265
std deviation of A          : 4.163331998932265


In [5]:
# np.random.randn, return a sample (or samples) from the “standard normal” distribution.
# It draw samples from a standard Normal distribution (mean=0, stdev=1).
A = np.random.randn(2,4)
print("Random A:\n", A)
print("Mean of A                     :",np.mean(A))
print("Standard deviation of A       :",np.std(A))

print("Mean of A (rows)              :",np.mean(A,axis=1))
print("Standard deviation of A (rows):",np.std(A,axis=1))



Random A:
 [[ 0.06481494 -2.28677356  1.81127356  0.81522015]
 [ 0.35310795  2.0319136   0.54510553 -0.40897142]]
Mean of A                     : 0.36571134371843517
Standard deviation of A       : 1.266226064250912
Mean of A (rows)              : [0.10113377 0.63028892]
Standard deviation of A (rows): [1.51144946 0.88440648]


In [6]:
# Construct an array by repeating given number by repetitions

a = np.tile(1, 5)
print(a)

[1 1 1 1 1]


In [7]:
b = np.tile([1, 2], 5)
print(b)

[1 2 1 2 1 2 1 2 1 2]


In [8]:
c = np.tile([1, 3], (5,2))
print(c)

[[1 3 1 3]
 [1 3 1 3]
 [1 3 1 3]
 [1 3 1 3]
 [1 3 1 3]]


In [9]:
c = np.tile([1, 3], (5,2)).T
print(c)

[[1 1 1 1 1]
 [3 3 3 3 3]
 [1 1 1 1 1]
 [3 3 3 3 3]]


In [10]:
d = np.tile([1, 3], (2,5))
print(d)

[[1 3 1 3 1 3 1 3 1 3]
 [1 3 1 3 1 3 1 3 1 3]]
